# Generated by Django 4.2.7 on 2024-09-05 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoIntroductionClipCutData',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('task_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='任务名称')),
                ('task_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='任务ID')),
                ('p_task_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='关联任务ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='目录名称')),
                ('txt', models.TextField(blank=True, null=True, verbose_name='解说文案')),
                ('tag', models.CharField(blank=True, max_length=30, null=True, verbose_name='序号任务')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '视频介绍应用',
                'verbose_name_plural': '视频介绍应用',
            },
        ),
    ]
